#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

# ── 依赖链接：交给 node 脚本（可重复执行，postinstall 也跑它）────────────────
# ★ 链接不能只写在这里：`npm install` 会清掉 node_modules 里它不认识的 junction
#   （实测装一个 ws 就删掉了 @deepseek-ai/* 与 @standard-schema），
#   所以同样的逻辑必须能被 postinstall 自动重跑 ⇒ 抽到 scripts/link-deps.mjs。
echo "=== Linking build dependencies ==="
DSH_CHECKOUT="$CHECKOUT" node scripts/link-deps.mjs

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json

# ── 把 project-shim/ 复制进 lib/ ────────────────────────────────────────────
# ★★ 这一步**不是可选的打包细节，是功能性的**：
#   `SimEngine` 把 `PYTHONPATH` 指向 shim（shim/ 提供 smbus 与 RPi.GPIO，
#   project-shim/ 提供 sitecustomize），项目进程靠它才连得上虚拟硬件。
#   而 package.json 的 `files` 只有 `["lib"]` ⇒ **不复制就等于发布一个跑不起来的包**。
#
# ★ 为什么开发期看不出问题：本地是 junction 直连源码目录，整个仓库都在，
#   随便写个相对路径都能找到 shim。**只有从 tgz 装出来才会暴露** ——
#   这正是本项目失败族里「看起来正常、实际全错」的又一例。
#
# ★ 排除 `__pycache__`：那是**本机 Python 版本**的字节码缓存（实测出现过
#   `smbus.cpython-314.pyc`），与解释器版本绑定，换台机器就是垃圾甚至误导。
#   随包发布的必须是源码。
echo "=== Copying project-shim → lib/project-shim ==="
rm -rf lib/project-shim
mkdir -p lib/project-shim
tar -C project-shim --exclude='__pycache__' -cf - . | tar -C lib/project-shim -xf -
SHIM_FILES="$(find lib/project-shim -type f | wc -l | tr -d ' ')"
if [ "$SHIM_FILES" -lt 4 ]; then
  echo "build: project-shim 复制结果可疑（只有 $SHIM_FILES 个文件，至少应有 4 个）" >&2
  exit 1
fi
echo "    $SHIM_FILES 个文件"

# ── 客户端 bundle ───────────────────────────────────────────────────────────
# ★★ 这一步**曾经漏掉，而且后果被误诊过**：
#   本脚本原来只编译宿主（tsc）+ 拷 shim，**从不构建客户端**。而客户端是
#   `npm run build:client`（tsdown）单独产出的 —— 于是：
#     · 我这边跑 `build.sh` 只更新 `lib/index.js`
#     · `lib/client.js` **停在并行会话上一次构建的时间点**
#     · 热重载照样报 `client ✓`（它只检查文件在不在）
#   ⇒ 表现是**界面停在旧代码上**，而宿主是新的 —— 两边版本不一致，
#     排查时却以为"已经构建过了"。
#
#   ⚠️ 这条属于本项目的失败族：**"构建成功"是近端，"两侧都是新的"才是远端。**
#     尤其本项目是**双半包**（宿主 + 客户端各自产出），只建一半不会有任何报错。
if node -e "process.exit(require('./package.json').scripts?.['build:client'] ? 0 : 1)"; then
  echo "=== Building client bundle (tsdown) ==="
  npm run build:client
else
  echo "=== 跳过客户端构建（package.json 里没有 build:client）==="
fi

# 构建标记：写进 lib/，由 lib/index.js 在加载时读取并暴露到 /api/capabilities。
# ★ 存在的理由：热重载可能报成功但模块并未真正换掉（实测踩过）。
#   没有这个标记时，「新代码没生效」与「新代码有 bug」在外部观测上无法区分。
node -e "
  const fs = require('fs');
  fs.writeFileSync('lib/build-stamp.json', JSON.stringify({
    builtAt: new Date().toISOString(),
    source: 'scripts/build.sh',
  }, null, 2) + '\n');
"
echo "=== Build complete (stamp: $(node -p "require('./lib/build-stamp.json').builtAt")) ==="